version: "2"
services:
  fintonic-code-challenge:
    container_name: fintonic-code-challenge
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      - PORT=3000
      - DB_URI=mongodb://mongo:27017/fintonic-code-challenge
      - DB_NAME=fintonic-code-challenge
      - JWT_SECRET=fintonic-code-challenge
  mongo:
    container_name: mongo
    image: mongo
